// chaos-taro/src/pages/index/index.tsx
import React, { useState, useEffect } from 'react';
import { View } from '@tarojs/components';
import { list } from '@/chaos/functions/Data';
import { navigateTo, getParams } from '@/chaos/functions/Taro';
import { doLogin } from '@/utils/login';
import './index.scss';

const Index: React.FC = () => {
  const [listData, setListData] = useState<[]>();
  useEffect(() => { load(); }, []);
  const load = async () => {
    setListData(await list('info'));
    const params = getParams();
    doLogin(params, true);
  };

  return (
    <View className='index'>
    </View>
  );
};

export default Index;

// chaos-uniapp/app/pages/index/index.vue
<template>
	<view class="page">

	</view>
</template>

<script>
	import {
		list
	} from '@/chaos/functions/Data';
	import {
		getParams,
		path,
		get
	} from '@/chaos/functions/Uni';
	import {
		doLogin
	} from '@/utils/login';

	export default {
		data() {
			return {
				loading: true,
				list: [],

			}
		},
		async created(props = {}) {
			this.list = await list("info");
			this.loading = false;
			doLogin(props, true);
		},
		methods: {

		}
	}
</script>

<style lang="scss" scoped>

</style>
